site_name: "Cuadratura Gauss-Legendre"
site_description: "Documentación del módulo gauss_quadrature con ejemplos y referencia automática"
site_author: "Sebastián Alí Sacasa Céspedes"

theme:
  name: material
  palette:
    primary: amber
    accent: red
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Inicio: index.md
  - Explicación del Método: explanation.md
  - Tutorial: tutorials.md
  - Referencia de Funciones: reference.md

plugins:
  - mkdocstrings:
      handlers:
        python: {}
